version: "3.8"

services:
  backend:
    image: Justinhadinata12345/wads-backend:latest
    restart: always
    environment:
      PORT: { PORT }
      NODE_ENV: { NODE_ENV }
      MONGODB_URI: { MONGODB_URI }
      JWT_SECRET: { JWT_SECRET }
      REFRESH_TOKEN_SECRET: { REFRESH_TOKEN_SECRET }
      GOOGLE_CLIENT_ID: { GOOGLE_CLIENT_ID }
      GOOGLE_CLIENT_SECRET: { GOOGLE_CLIENT_SECRET }
      GOOGLE_CALLBACK_URL: { GOOGLE_CALLBACK_URL }
      GEMINI_API_KEY: { GEMINI_API_KEY }
      FIREBASE_API_KEY: { FIREBASE_API_KEY }
      FIREBASE_AUTH_DOMAIN: { FIREBASE_AUTH_DOMAIN }
      FIREBASE_PROJECT_ID: { FIREBASE_PROJECT_ID }
      FIREBASE_STORAGE_BUCKET: { FIREBASE_STORAGE_BUCKET }
      FIREBASE_MESSAGING_SENDER_ID: { FIREBASE_MESSAGING_SENDER_ID }
      FIREBASE_APP_ID: { FIREBASE_APP_ID }
      FIREBASE_MEASUREMENT_ID: { FIREBASE_MEASUREMENT_ID }

    ports:
      - "3010:3010"

  frontend:
    image: Justinhadinata12345/wads-frontend:latest
    restart: always
    depends_on:
      - backend
    ports:
      - "3009:3009"
